pipeline:
  build:
    image: dock.pw.fr/pw/debpkg:${DEBIAN_VERSION}
    commands:
      - echo "deb http://ftp.fr.debian.org/debian/ ${DEBIAN_VERSION}-backports main" > /etc/apt/sources.list.d/backports.list
      - apt-get update >/dev/null
      - '[ "${DEBIAN_VERSION}" = "wheezy" ] && apt-get install -y apache2-prefork-dev php5-dev || apt-get install -y apache2-dev'
      - '[ "${DEBIAN_VERSION}" = "stretch" ] && apt-get install -y php7.0-dev || apt-get install -y php5-dev'
      - '[ "${DEBIAN_VERSION}" = "stretch" ] && apt-get install -y cmake libhiredis-dev libhiredis-dbg valgrind redis-server clang libjson-c-dev || apt-get install -y -t ${DEBIAN_VERSION}-backports  cmake libhiredis-dev libhiredis-dbg valgrind redis-server clang libjson-c-dev'
      - sed -i -e "s/6379/6380/" /etc/redis/redis.conf
      - echo "unixsocket /var/run/redis/redis-webconf.sock" >> /etc/redis/redis.conf
      - /etc/init.d/redis-server start
      - tests/setup_tests.sh
      - scan-build make
      - scan-build make test_redis
      - make
      - make test_redis
      - ./test_redis website.com
      - valgrind ./test_redis website.com
      - dpkg-buildpackage -b

  pkg:
    image: appleboy/drone-scp
    host: pippin.planet-work.net
    username: pkg
    source: ../*.deb
    target: incoming/libapache2-mod-vhs/${DEBIAN_VERSION}
    when:
        event: tag

  aptly:
    image: appleboy/drone-ssh
    host: pippin.planet-work.net
    user: pkg
    script:
      - aptly repo add debian-${DEBIAN_VERSION} incoming/libapache2-mod-vhs/${DEBIAN_VERSION} && aptly publish update ${DEBIAN_VERSION} debian 
    when:
      event: tag

matrix:
  DEBIAN_VERSION:
    - wheezy
    - jessie
    - stretch

